# Generated by Django 5.2.3 on 2025-06-23 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_meta_presupuesto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorteMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_corte', models.DateField()),
                ('mes_cortado', models.IntegerField()),
                ('año_cortado', models.IntegerField()),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_mes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldos_cuentas', models.JSONField(default=dict)),
                ('mantener_saldos', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes_mes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_corte'],
                'unique_together': {('usuario', 'mes_cortado', 'año_cortado')},
            },
        ),
    ]
