# Generated by Django 5.2.3 on 2025-06-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_cortemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='institucion_financiera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Peso Argentino'), ('USD', 'Dólar Estadounidense'), ('EUR', 'Euro'), ('BRL', 'Real Brasileño'), ('CLP', 'Peso Chileno'), ('COP', 'Peso Colombiano'), ('MXN', 'Peso Mexicano'), ('PEN', 'Sol Peruano'), ('UYU', 'Peso Uruguayo'), ('VES', 'Bolívar Venezolano')], default='ARS', max_length=3),
        ),
    ]
