# Generated by Django 5.2.3 on 2025-06-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastocompartido',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
