# Generated by Django 5.2.3 on 2025-06-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_add_activo_to_gastocompartido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionusuario',
            name='moneda_principal',
            field=models.CharField(choices=[('ARS', 'Peso Argentino'), ('USD', 'Dólar Estadounidense'), ('EUR', 'Euro'), ('BRL', 'Real Brasileño'), ('CLP', 'Peso Chileno'), ('COP', 'Peso Colombiano'), ('MXN', 'Peso Mexicano'), ('PEN', 'Sol Peruano'), ('UYU', 'Peso Uruguayo'), ('VES', 'Bolívar Venezolano')], default='ARS', max_length=3),
        ),
        migrations.AlterField(
            model_name='configuracionusuario',
            name='zona_horaria',
            field=models.CharField(choices=[('America/Argentina/Buenos_Aires', 'Argentina (Buenos Aires)'), ('America/New_York', 'Estados Unidos (Nueva York)'), ('Europe/Madrid', 'España (Madrid)'), ('America/Sao_Paulo', 'Brasil (São Paulo)'), ('America/Santiago', 'Chile (Santiago)'), ('America/Bogota', 'Colombia (Bogotá)'), ('America/Mexico_City', 'México (Ciudad de México)'), ('America/Lima', 'Perú (Lima)'), ('America/Montevideo', 'Uruguay (Montevideo)'), ('America/Caracas', 'Venezuela (Caracas)')], default='America/Argentina/Buenos_Aires', max_length=50),
        ),
    ]
